// NOTE: This file is automatically generated by the deploy script.
// It is not meant to be edited manually; your changes will be overwritten.
import { ChainId } from "@thirdweb-dev/sdk";
export const IS_DEV_ENV = process.env.NODE_ENV === "development";

// Update these values to match your project setup.
export const DEV_CHAIN_ID = ChainId.Localhost;
export const DEV_CHAIN_ID_ENUM_NAME = "Localhost";
export const PRODUCTION_CHAIN_ID = ChainId.Polygon
export const PRODUCTION_CHAIN_ID_ENUM_NAME = "Polygon";

// Constant variable that will be used throughout the app.
// Uses local host network if in development, otherwise uses the production chain ID.
export const BLOCKCHAIN_ID = IS_DEV_ENV ? DEV_CHAIN_ID : PRODUCTION_CHAIN_ID;

export const internalContractAddresses = {
    [DEV_CHAIN_ID]: {
      greeter: {
        "address": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
        "abi": [{"inputs":[{"internalType":"string","name":"_greeting","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"newGreeting","type":"string"}],"name":"GreetingChanged","type":"event"},{"inputs":[],"name":"greet","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_greeting","type":"string"}],"name":"setGreeting","outputs":[],"stateMutability":"nonpayable","type":"function"}]
      }
    },
    [PRODUCTION_CHAIN_ID]: {
      greeter: {
        "address": "<INSERT PRODUCTION ADDRESS HERE>", // Once you deploy your smart contract to production (such as Mainnet), add the address manually here.
        "abi": [{"inputs":[{"internalType":"string","name":"_greeting","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"newGreeting","type":"string"}],"name":"GreetingChanged","type":"event"},{"inputs":[],"name":"greet","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_greeting","type":"string"}],"name":"setGreeting","outputs":[],"stateMutability":"nonpayable","type":"function"}]
      }
    },
  };

const contractAddresses = IS_DEV_ENV
  ? internalContractAddresses[DEV_CHAIN_ID]
  : internalContractAddresses[PRODUCTION_CHAIN_ID];

export default contractAddresses;
